### ISSUE TITLE
newDesigner.sh fails if you try to download a macOs product

### ISSUE THREAD

**Issue by ivy-lli** [ivy-rew/jenkinsCli#5]
Hi 

I currently have a problem that the `newDesigner.sh` script fails to download a macOS product.

my .env settings: `DESIGNER_PATTERN=AxonIvyDesigner.*_macOS_x64.zip`

I think the problem is that the default core_product build does not provide a macOS product. So it would be cool if the newDesigner command tries to download the macOS product from the corresponding build. 

Or do I miss something?

**Comment by ivy-rew** [comment]
Yes, true. Didn't think about that and will try to fix it.
Meanwhile you may just add the correct branch manually > newDesigner.sh L13
